[package]
name = "imgcat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
base64 = "0.22.1"
clap = { version = "4.5.7", features = ["derive"] }
reqwest = { version = "0.12.5", features = ["blocking"] }
