name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build on ${{ matrix.platform.os }} with rust to target ${{ matrix.platform.target }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
          - target: x86_64-unknown-linux-musl
            os: ubuntu-20.04
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-20.04
          - target: aarch64-unknown-linux-musl
            os: ubuntu-20.04
          - target: aarch64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-apple-darwin
            os: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure - Basics
        run: |
          git config --global user.email "chenych11@gmail.com"
          git config --global user.name "cyc"

      - name: Configure - Unix-like
        run: |
          if [[ "${{ matrix.platform.target }}" == *musl* || "${{ matrix.platform.target }}" == *aarch64* ]]; then
            echo "FLAGS=--features reqwest/native-tls-vendored" >> $GITHUB_ENV
          else
            echo "FLAGS=" >> $GITHUB_ENV
          fi
        if: ${{ ! contains(matrix.platform.os, 'windows') }}

      - name: Configure - Windows
        run: echo "FLAGS=--features reqwest/native-tls-vendored" | Out-File -FilePath $env:GITHUB_ENV -Append
        if: ${{ contains(matrix.platform.os, 'windows') }}

      - name : Configure - Dependencies - Ubuntu
        run: sudo apt-get update --yes && sudo apt-get install --yes libssl-dev
        if: ${{ contains(matrix.platform.os, 'ubuntu') }}

      - name: Configure - Dependencies - musl
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
        if: ${{ contains(matrix.platform.target, 'musl') }}

      - name: Show env on Unix-like system
        run: echo FLAGS = $FLAGS
        if: ${{ ! contains(matrix.platform.os, 'windows') }}

      - name: Show env on Windows
        run: echo FLAGS = $env:FLAGS
        if: ${{ contains(matrix.platform.os, 'windows') }}

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Build ${{ matrix.platform.target }}
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: "stable"
          args: "--locked --release $FLAGS"

      # - name: Run tests
      #  uses: houseabsolute/actions-rust-cross@v0
      #  with:
      #    command: "test"
      #    target: ${{ matrix.platform.target }}
      #    toolchain: ${{ matrix.toolchain }}
      #    args: "--locked --release"
      #  if: ${{ !matrix.platform.skip_tests }}

      - name: Archive
        id: packaging
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          if [[ "${{ matrix.platform.target }}" == *windows* ]]; then
            artifact=imgcat-${{ matrix.platform.target }}.${{  github.ref_name }}.zip
            7z a ../../../$artifact imgcat.exe
          else
            artifact=imgcat-${{ matrix.platform.target }}.${{  github.ref_name }}.tar.gz
            tar czvf ../../../$artifact imgcat
          fi
          echo "ARTIFACT=$artifact" >> $GITHUB_OUTPUT
          cd -

      - name: Generate SHA-256
        shell: bash
        run: |
          artifact=${{ steps.packaging.outputs.ARTIFACT }}
          echo "artifact=$artifact"
          shasum -a 256 "$artifact" | cut -d' ' -f1 > "$artifact".sha256
        if: ${{ !contains(matrix.platform.os, 'windows') }}

      - name: Generate SHA-256 on Windows
        shell: powershell
        run: |
          (certutil -hashfile ${{ steps.packaging.outputs.ARTIFACT }} SHA256)[1] | `
           Out-File -Encoding ASCII ${{ steps.packaging.outputs.ARTIFACT }}.sha256
        if: ${{ contains(matrix.platform.os, 'windows') }}

      - name: Publish
        uses: svenstaro/upload-release-action@v2
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: ${{ steps.packaging.outputs.ARTIFACT }}*
            overwrite: true
            file_glob: true
